# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='_file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='file size'),
        ),
    ]

